### ISSUE TITLE
Benchmarking pure code with heavily optimising JIT compilers

### ISSUE THREAD

**Issue by zwilias** [BrianHicks/elm-benchmark#11]
The properties that make Elm so nice to work with (i.e. pure functions, type safety, etc) make it easy for JavaScript compilers to optimise. While that is certainly a very good thing, it does make it exceedingly hard to write micro-benchmarks with any degree of certainty.

One thing we’re doing with micro-benchmarks, is calling the same function over and over again, with the same inputs, discarding the result. Given the simplicity of the function, the JIT is perfectly capable of noticing that it will always return the exact same result, which means it doesn’t actually have to do any computation at all. The more advanced JIT compilers become, the harder it will become to write (micro)benchmarks that represent reality.

The benchmarking library for Elm currently doesn’t keep any reference to the result of function calls made as part of the benchmark. This makes things slightly less predictable, as the JIT may just as well decide to replace the entire function by a no-op: a side-effect free function whose result is discarded is essentially a no-op.

This issue is already hinted at, and discussed to some degree in #7 

So, what can we do?

- figure out a way to vary input, for example cycling through a preset list of possible inputs, or hooking it up to a random generator
- figure out a way to not disregard the results, but keep track of them - which would also open up to possibility of *verifying* them
- _bonus points_: figure out a way to create statefull benchmarks that fold variable input over a state. Say we're benchmarking a Dict, and have a source that creates random `update/insert/remove` calls according to some preconfigured distribution. Handing that same source to two Dict implementations would allow figuring out which one is better at which type of operation under a mixed and configurable load.

**Comment by zwilias** [comment]
Re https://ellie-app.com/FssWM2pTzka1/0

Based on my research (going through the crankshaft IR using [irhydra](http://mrale.ph/irhydra/2/)), the magic is _actually_ in `thunk` being optimized.

**Without** the "optimization buster", `thunk` can be either `withFunction` or `withPatternMatch`. The limited variance allows the JIT optimizer to inline `Tuple.first`; which is then optimized away due to the parameter being constant and the result not being used: it literally becomes a no-op. `withPatternMatch` is only partially optimized; the return statement still happens.

**With** the buster, there are three options for `thunk`: the "noop" we defined (`\() -> ()`), `withFunction` or `withPatternMatch`. Due to the higher variance, more deoptimization happens; resulting in the `Tuple.first` call still happening. Note that it *is* still inlined, which is why the `withPatternMatch` performance is roughly the same, rather than higher as one would expect.

Note that replacing the buster by a `benchmark1` call hence reverts to the first scenario, as can be checked here: https://ellie-app.com/LNFcg2v2s6a1/0

**Comment by BrianHicks** [comment]
Ok, sorry for taking so long to get on this. Thanks for all this great research!

Can you tell if there are certain situations where the JIT breaks things? If so, could we detect them and automatically run the buster? If no, does it make sense to you to *always* run the buster? (I think it may.)
