### ISSUE TITLE
Make benchmark output easier to scan

### ISSUE THREAD

**Issue by jwoudenberg** [BrianHicks/elm-benchmark#12]
A bit of styling nitpicking: the information in the report is a bit compact, making it harder to home in on the piece of information you're looking for by quickly scanning the page.

<img width="722" alt="screen shot 2017-06-05 at 14 14 10" src="https://cloud.githubusercontent.com/assets/1525551/26783603/5e0c9ee8-49f9-11e7-8a5b-f89702881dc8.png">

**Comment by BrianHicks** [comment]
how about these?

![image](https://user-images.githubusercontent.com/355401/33812104-e4915f7e-dddf-11e7-9520-85d365649220.png)

and

![image](https://user-images.githubusercontent.com/355401/33812106-eb38c1d2-dddf-11e7-9d17-3157af75edbe.png)

**Comment by jwoudenberg** [comment]
😻 😻 😻 😻 😻 😻 😻

**Comment by BrianHicks** [comment]
shipped!
