### ISSUE TITLE
Allow benchmarks to be colocated with the code they performance test

### ISSUE THREAD

**Issue by jwoudenberg** [BrianHicks/elm-benchmark#15]
Elm-test is moving towards allowing you to place your tests next to the code they test and having the runner be able to find and run all the tests in a particular Elm module.

This might be a nice approach for benchmarks to take too. Colocating benchmarks with tests would allow you to easily run the benchmarks relevant to what you're doing, by pointing some hypothetical benchmark runner tool to the Elm module you changed.

**Comment by BrianHicks** [comment]
moved to elm-explorations/benchmark#6
