### ISSUE TITLE
Allow for displaying benchmark results in the view as soon as possible

### ISSUE THREAD

**Issue by fredcy** [BrianHicks/elm-benchmark#2]
Per discussion in the Elm Slack, benchmark runs can take a long time and so it can be helpful to display results incrementally in the view showing the progress of the overall suite as individual benchmark results become available.

It's possible to use such incremental results to display a dynamic graph (such as a line chart) that displays more and more data points as the suite runs.  See https://fredcy.github.io/elm-core-benchmark/ for example.

**Comment by BrianHicks** [comment]
The benchmark results are incremental now. I've opened #3 and #4 to cover the other things. Feel free to open more issues if I've missed something. :)
