### ISSUE TITLE
Improve Benchmark data structure

### ISSUE THREAD

**Issue by basile-henry** [BrianHicks/elm-benchmark#23]
## Current state

This is the current data structure used to organise benchmarks:

``` elm
type Benchmark
    = Benchmark String Operation Status
    | Group String (List Benchmark)
    | Compare String Benchmark Benchmark
```

It is simple and concise, however it allows for nonsensical benchmark structures. Do we want to be able to compare a `Group` with a single `Benchmark`? Or compare two comparisons?

When some of these awkward benchmark structures are used we get the following message:

> Sorry, I can't compare these kinds of benchmarks directly.
> Here are the serialized values so you can do it yourself:

It is nice to get some results back, so the user can make sense of it as they please. But it seems like no one would rely on such a feature (I would love to hear an example where this is useful!).

## 1st suggestion

My suggestion is to use a data structure that disallows possible unwanted states. I have identified the following features that are wanted from the data structure:

- Named simple or comparison benchmarks (possibly more than 2 benchmarks in a comparison in the future)
- A way to organise the benchmarks in named groups.

The following data structure gives such features while disallowing the unwanted states:

``` elm
type Benchmark
    = Benchmark String Operation Status


type BenchmarkTree
    = Simple Benchmark
    | Compare String Benchmark Benchmark
    | Group String (List BenchmarkTree)
```

I believe this is better, but I would like to go even further.

## 2nd suggestion

I don't think a `Group` should hold a mix of subgroups and `Simple`/`Compare` benchmarks. If we disallow such a mix it opens up the possibility for other ways of rendering the benchmark results. Benchmarks from the same group can be presented as belonging together (on a table, a chart or anything else).

I have in mind using bar charts to show results from a given group of benchmarks where it makes sense to put results on the same graph side by side. The idea of using charts was already mentioned in #4. Comparisons can be grouped together on the bar chart. Confidence intervals can be used to show the standard deviation of the benchmarks. Hints can be used to reveal even more information such as **total runtime** and **sampling**.

Something like this but nicer (using elm-plot):

![bar charts](https://upload.wikimedia.org/wikipedia/commons/d/df/Confidenceinterval.png)

This is a data structure that separates the grouping structure from the benchmarks in order to disallow mixing groups and benchmarks:

``` elm
type Benchmark
    = Benchmark String Operation Status


type BenchmarkEntity
    = Simple Benchmark
    | Compare String Benchmark Benchmark


type BenchmarkTree
   = Group String (List BenchmarkEntity)
   | Tree String (List BenchmarkTree)
```

## Implementation

I would love to write a PR to update `elm-benchmark` with this new data structure (or a modified version of it if preferred). I do realise this is a major change and may be unwanted. However if it is something of interest, maybe it should come with version `2.0.0` when Elm `0.19` is released.

I have opened this issue to gather feedback on such a change and whether or not I should spend the time writing a PR for it. :smile:

**Comment by BrianHicks** [comment]
Hey, thanks for the thought you've put into this! I approached it from a similar angle when originally doing the work but stopped short of the solution you propose in favor of getting accurate measurements. Now may be a good time to revisit it!

So, my thoughts: `Benchmark` is a good name. `BenchmarkEntity` and `BenchmarkTree`… not so much. We also don't need nearly that many types! What do you think of, instead:

```elm
type Benchmark
    = Benchmark (List (String, Operation, Status)) -- or maybe Benchmark String (namedBenchmarks)
    | Group String (List Benchmark)
```

This solves for running a single benchmark (provided we use [nonempty lists](http://package.elm-lang.org/packages/mgold/elm-nonempty-list/latest/List-Nonempty)) as well as comparisons of arbitrary length. We'd have to do some internal shuffling to make this work out, but "code is the easy part" right?

You're correct that it would require a 2.0.0 release. I'm fine with that. I *do* want to hold off until 0.19 (tracking in #20.) But there's no reason we can't prepare these kinds of changes beforehand. :)

Another thing to think about, while you've got the API in your head: can you think of any ways we could reduce common errors and use the type system to force people to write better benchmarks? I welcome more issues with any additional thoughts like this, but let's keep discussion here focused on your proposal. 😄

**Comment by basile-henry** [comment]
You are right, the names for `BenchmarkEntity` and `BenchmarkTree` are not good. I really like your idea of modeling comparable benchmarks with a `NonEmpty` list, it would make them much more extensible!

With the data type you are suggesting you still end up with benchmarks mixed in with groups at various levels of the benchmark tree. That may not be an issue but it might make outputting interesting graphs (like the bar plot I mentioned) less straight forward.

My idea of separating the grouping structure from the actual benchmark was originally inspired by a Haskell testing framework called [`tasty`](https://hackage.haskell.org/package/tasty-0.11.2.5/docs/Test-Tasty.html). But after looking more closely at its source code it has a very similar data type to yours, so I am probably overthinking the *mixing groups with benchmark* aspect.

> can you think of any ways we could reduce common errors and use the type system to force people to write better benchmarks?

Is there any particular common error that you are thinking about? Your `NonEmpty` list model seems to completely solve the current `Compare` case where you can model unwanted states.

However there might be a few concerns with using `NonEmpty` lists and maybe simple lists would be good enough:

- It would add a new dependency on `elm-benchmark`
- If the `NonEmpty` list is part of the API:
  + It also adds a dependency on the benchmarks of the users
  + Complexity overhead for users not familiar with other types of lists and having to use third party libraries
- Using an empty list for a group or a comparable benchmark has a couple of possible implementations:
  + The group or the benchmark is completely skipped (and does not appear in the view)
  + They are skipped but do appear in the view (so the name shows up)
  + They appear as if they run a trivial benchmark in the form: `benchmark "Empty benchmark" identity`

I'd be happy implementing your version of the data type as it seems reasonable. Is there any particular reason you favour tuples over records? It might make writing the library easier if you use something along the lines of:

``` elm
type Benchmark
    = Benchmark (List { name : String, operation : Operation, status : Status }) 
    | Group String (List Benchmark)
```

Or with a named alias in order to get a constructor.

**Comment by BrianHicks** [comment]
> With the data type you are suggesting you still end up with benchmarks mixed in with groups at various levels of the benchmark tree. That may not be an issue but it might make outputting interesting graphs (like the bar plot I mentioned) less straight forward.

I don't think this will be an issue. If something's meant to be compared, it should be in a single benchmark. Groups are for the *organization* sense of grouping, not the *runtime* sense. This is maybe a smell! 😝 I took this API to mirror the API in elm-test at the time, maybe it's time to revisit that as well.

> - It would add a new dependency on `elm-benchmark`

I'm not concerned about this in the slightest. This is solely a dev tool where the compiled size of the output doesn't matter, as long as it's consistent.

> Is there any particular reason you favour tuples over records?

None, other than it being easier to type in a GitHub comment box. 😝 Things with three or more fields should probably live in a record for clarity's sake.

But, actually, I had a thought: benchmarks should not have duplicate names. It will cause problems visualizing, etc. It would be better to use a `Dict`:

```elm
type Benchmark
    = Benchmark (Dict String (Operation, Status)) 
    | Group String (List Benchmark)
```

… in which case we could use a tuple.

If you want to get started, this design seems fine. I'm interested to know of any other improvements you find while simplifying this data structure. Once you're done, I will probably give the whole thing a good going-over to refactor the engine. I will wait until I see a PR from you, so please do let me know if you decide you're not interested in this work so I can do it myself prior to the 0.19 release. 😄

**Comment by basile-henry** [comment]
Using a `Dict` makes sense! :smile: 

Before I get started with the PR, there is still a small difference between the current version and this proposal: `Compare` both has a name or description for the comparison and for each one of the benchmarks. Is this something we would like to keep? Or are we giving up this naming hierarchy for the more generic `Dict` approach?

**Comment by BrianHicks** [comment]
Well, an extra name is invalid in the single case but essential for comparisons. So maybe we need another union type/data structure. I'm not sure what to call it though! Maybe we can take advantage of the namespacing here to call it `Kind` or `BenchmarkKind`?

**Comment by zwilias** [comment]
I've been experimenting. The coupling to that datastructure is a little annoying, and makes it hard for a custom runner to choose a different structure. So I've been thinking, and a little reorganization _may_ be in order.

## `benchmark-primitives`
> Should not be coupled to specific structure. It is concerned with the primitives: what is a benchmark, how does it operate, and how do I get a result

- `type Benchmark = Benchmark String Operation Status` is the most basic thing that describes one single benchmark.
- `step : Benchmark -> Maybe (Task Never Benchmark)` is how you step a single benchmark
- `type Report = Report String Status` describes the status of a benchmark
- `Report.fromBenchmark : Benchmark -> Report` allows inspecting the state of a benchmark
- encode/decode: provide a common JSON format for a single benchmark
- `benchmark` -> `benchmark8` to actually construct a benchmark
- `withSize : Time -> Benchmark -> Benchmark` to fixup timing

I think that's basically all?

By not coupling to a structure, different runners are free to implement whichever crazy structure on top of that. A CLI runner dedicated to comparing a baseline vs a non-empty list of variations on it? Sure, go right ahead.

## `benchmark`
> The current runner and higher level API. This one should care about structure.
I rather like the proposal outlined in the first post, as far as datastructures go. Naming is hard, but doesn't mean it should be avoided.

```elm
type Benchmark
    = Single Primitive.Benchmark
    | Compare String Primitive.Benchmark Primitive.Benchmark
    | Group String (NonEmptyList Benchmark)
```

---

By separating those concerns, you allow
- runners to use whichever data-structure best fits them
- CLI runners to not have HTML-related dependencies

At the cost of
- potentially reimplementing that same structure across multiple runners

---

So yeah, there are trade-offs. As with all things, I suppose :)

**Comment by BrianHicks** [comment]
I like the idea of separating the benchmarks into a lower and higher level. I'm concerned, though, that this creates more structures that we need to keep in sync. Operation is already one too many, IMO, so perhaps Benchmark should move into the lowlevel package and wrap Operation instead.

I don't think there's enough justification to remove grouping. It's common to all runners, and if someone needs a different organization, they're free to wrap the API.

This aside, there will probably only ever be three runners: the browser, the CLI, and the racing site described in the Elm projects repo. Sure, there may be more, but probably a small enough number that we shouldn't hamstring ourselves for optimizing for very many more.

I plan on revisiting this in depth after elm-conf.

**Comment by zwilias** [comment]
`Operation` wouldn't need to be exposed, though, if/how `Operation` and `Benchmark` are separated is an implementation detail. I agree, though, `Operation` is currently a little pointless, I don't think any consumer of the library has a need to know about these "untyped thunks".

As for wrapping the API: if the API only exposes a complex type for benchmarks, wrapping it means you're still something that _might_ be a group or a comparison. Separating the data from the structure that holds it doesn't seem like such a crazy idea, does it?

Concerning the runners: sure, I don't mean we should make things overly complex to support every possible scenario. Open/closed principle in this case doesn't seem to make things more complex, though? Though really, as long as the `primitives` has a proper and exposed API, the "default" structure could be part of that same repo, and reusable across any runner that wishes to use it. 

Doing the minimal thing that could possibly work and building the rest on top of that seems like a good idea, in general.

**Comment by BrianHicks** [comment]
In this case we clearly have a different definition of "the minimal thing". 😜

So, the first goal of the library is not to be accurate, but consistent. In order to be consistent, we need a consistent structure and ways to build around it. That's why I'm saying that it should be a library concern: the structure of the data is part of the data.

But I don't think our goals are in opposition. What about:

- Benchmark.LowLevel
   - Benchmark
   - benchmarkN
   - step
- Benchmark
   - Benchmark
      - Named list of Benchmarks
      - Named group of Benchmarks
   - wrapping single constructors
   - step for local Benchmark

Best of both worlds, right? The structure relies on the single types, and the default runners rely on the structure. Serialization would probably take place with en/decoders at both levels for report purposes (otherwise console runners would be too difficult)

This would have a nice side effect of splitting up that horrible step function I wrote!

But again, this should be optimized for a small handful of runners, not everything under the sun. I think this sounds like a good compromise with flexibility but sufficient safety.

**Comment by zwilias** [comment]
With that module structure, I think we _exactly_ agree! `LowLevel` being the minimal thing, `Benchmark` being a nice "ready for consumption" API on top of that. I think that looks great! <3

**Comment by BrianHicks** [comment]
@basile-henry: what do you think? How does this affect what you've done so far? I think we may be able to make some of these changes concurrently, but most of them will cause conflicts on merge.

**Comment by BrianHicks** [comment]
@zwilias do you think you could distill this discussion down to a separate issue, please? I'd do it myself but I'm mobile this weekend. 🙂

**Comment by basile-henry** [comment]
@BrianHicks I was playing around with the different data structures we discussed but nothing serious so far. Using modules to separate the internal and external API seems to be a neat approach. Good job @zwilias!

I might give a go to this module separation but if you prefer doing it I understand, you're much more familiar with the code base and it could prevent a lot of back and forth.

Why do you want to open a separate issue? Is it just to make it cleaner or are there different parts to this issue I am not seeing?

**Comment by BrianHicks** [comment]
It's because I wanted to keep that discussion  separate from your work, if that work can be done separately. It's also good to have fresh issues for things. Linking is easy enough, and distilling decisions down removes ambiguity in discussion. Buuuut we can and should keep discussing it here. It's part and parcel of what you've proposed.

**Comment by zwilias** [comment]
Right. So I'll open a new issue to discuss an alternative module structure, whereas this issue can stay focused on structuring the higher level `Benchmark` type. Does that sound good to everyone?

**Comment by BrianHicks** [comment]
If you wanna sum it up here that'd be fine too. They're rather intricately linked.

**Comment by BrianHicks** [comment]
Hey! elm-conf is over and I'm gonna give this a go unless you're working on it already?

**Comment by zwilias** [comment]
Not really - I got sidetracked a little. I did end up needing something along these lines in a different project, tho, and mashed up this thing: https://github.com/zwilias/bench-series/blob/master/src/Series/LowLevel.elm

Since we currently expose `operation`, `Operation` and `sample`, this is pretty trivial to replicate in a standalone repo 😸

**Comment by basile-henry** [comment]
Hey @BrianHicks! Yes, definitely give this a go. I unfortunately didn't really have the time to work on this (I just started a new job!). I'm looking forward to watching elm-conf videos, thanks for organizing it! :smile:
