### ISSUE TITLE
Benchmark.Runner report hides the top of a long list

### ISSUE THREAD

**Issue by justinmimbs** [BrianHicks/elm-benchmark#37]
When the list of benchmarks is taller than the viewport, it appears vertically centered, clipping both the top and bottom. The page allows scrolling down to the bottom, but not up to the top.

https://ellie-app.com/8rVXQ3tPVa1/0

**Comment by BrianHicks** [comment]
Thanks for reporting! I'm attaching a screenshot here so I can make sure to get before/after when working on this.

![image](https://user-images.githubusercontent.com/355401/34213682-9281469e-e565-11e7-9744-cea192b6b3d9.png)

I'm also gonna tag this with the easy to fix labels. Maybe some kind person will pick this up before I can get to it!
